export interface Country {
  code: string;
  name: string;
  nameAr: string;
  phoneCode: string;
}

// All countries sorted alphabetically
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", nameAr: "أفغانستان", phoneCode: "+93" },
  { code: "AL", name: "Albania", nameAr: "ألبانيا", phoneCode: "+355" },
  { code: "DZ", name: "Algeria", nameAr: "الجزائر", phoneCode: "+213" },
  { code: "AD", name: "Andorra", nameAr: "أندورا", phoneCode: "+376" },
  { code: "AO", name: "Angola", nameAr: "أنغولا", phoneCode: "+244" },
  { code: "AG", name: "Antigua and Barbuda", nameAr: "أنتيغوا وبربودا", phoneCode: "+1268" },
  { code: "AR", name: "Argentina", nameAr: "الأرجنتين", phoneCode: "+54" },
  { code: "AM", name: "Armenia", nameAr: "أرمينيا", phoneCode: "+374" },
  { code: "AU", name: "Australia", nameAr: "أستراليا", phoneCode: "+61" },
  { code: "AT", name: "Austria", nameAr: "النمسا", phoneCode: "+43" },
  { code: "AZ", name: "Azerbaijan", nameAr: "أذربيجان", phoneCode: "+994" },
  { code: "BS", name: "Bahamas", nameAr: "الباهاما", phoneCode: "+1242" },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", phoneCode: "+973" },
  { code: "BD", name: "Bangladesh", nameAr: "بنغلاديش", phoneCode: "+880" },
  { code: "BB", name: "Barbados", nameAr: "بربادوس", phoneCode: "+1246" },
  { code: "BY", name: "Belarus", nameAr: "بيلاروسيا", phoneCode: "+375" },
  { code: "BE", name: "Belgium", nameAr: "بلجيكا", phoneCode: "+32" },
  { code: "BZ", name: "Belize", nameAr: "بليز", phoneCode: "+501" },
  { code: "BJ", name: "Benin", nameAr: "بنين", phoneCode: "+229" },
  { code: "BT", name: "Bhutan", nameAr: "بوتان", phoneCode: "+975" },
  { code: "BO", name: "Bolivia", nameAr: "بوليفيا", phoneCode: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", nameAr: "البوسنة والهرسك", phoneCode: "+387" },
  { code: "BW", name: "Botswana", nameAr: "بوتسوانا", phoneCode: "+267" },
  { code: "BR", name: "Brazil", nameAr: "البرازيل", phoneCode: "+55" },
  { code: "BN", name: "Brunei", nameAr: "بروناي", phoneCode: "+673" },
  { code: "BG", name: "Bulgaria", nameAr: "بلغاريا", phoneCode: "+359" },
  { code: "BF", name: "Burkina Faso", nameAr: "بوركينا فاسو", phoneCode: "+226" },
  { code: "BI", name: "Burundi", nameAr: "بوروندي", phoneCode: "+257" },
  { code: "CV", name: "Cabo Verde", nameAr: "الرأس الأخضر", phoneCode: "+238" },
  { code: "KH", name: "Cambodia", nameAr: "كمبوديا", phoneCode: "+855" },
  { code: "CM", name: "Cameroon", nameAr: "الكاميرون", phoneCode: "+237" },
  { code: "CA", name: "Canada", nameAr: "كندا", phoneCode: "+1" },
  { code: "CF", name: "Central African Republic", nameAr: "جمهورية أفريقيا الوسطى", phoneCode: "+236" },
  { code: "TD", name: "Chad", nameAr: "تشاد", phoneCode: "+235" },
  { code: "CL", name: "Chile", nameAr: "تشيلي", phoneCode: "+56" },
  { code: "CN", name: "China", nameAr: "الصين", phoneCode: "+86" },
  { code: "CO", name: "Colombia", nameAr: "كولومبيا", phoneCode: "+57" },
  { code: "KM", name: "Comoros", nameAr: "جزر القمر", phoneCode: "+269" },
  { code: "CG", name: "Congo", nameAr: "الكونغو", phoneCode: "+242" },
  { code: "CD", name: "Congo (DRC)", nameAr: "الكونغو الديمقراطية", phoneCode: "+243" },
  { code: "CR", name: "Costa Rica", nameAr: "كوستاريكا", phoneCode: "+506" },
  { code: "CI", name: "Côte d'Ivoire", nameAr: "ساحل العاج", phoneCode: "+225" },
  { code: "HR", name: "Croatia", nameAr: "كرواتيا", phoneCode: "+385" },
  { code: "CU", name: "Cuba", nameAr: "كوبا", phoneCode: "+53" },
  { code: "CY", name: "Cyprus", nameAr: "قبرص", phoneCode: "+357" },
  { code: "CZ", name: "Czech Republic", nameAr: "التشيك", phoneCode: "+420" },
  { code: "DK", name: "Denmark", nameAr: "الدنمارك", phoneCode: "+45" },
  { code: "DJ", name: "Djibouti", nameAr: "جيبوتي", phoneCode: "+253" },
  { code: "DM", name: "Dominica", nameAr: "دومينيكا", phoneCode: "+1767" },
  { code: "DO", name: "Dominican Republic", nameAr: "جمهورية الدومينيكان", phoneCode: "+1809" },
  { code: "EC", name: "Ecuador", nameAr: "الإكوادور", phoneCode: "+593" },
  { code: "EG", name: "Egypt", nameAr: "مصر", phoneCode: "+20" },
  { code: "SV", name: "El Salvador", nameAr: "السلفادور", phoneCode: "+503" },
  { code: "GQ", name: "Equatorial Guinea", nameAr: "غينيا الاستوائية", phoneCode: "+240" },
  { code: "ER", name: "Eritrea", nameAr: "إريتريا", phoneCode: "+291" },
  { code: "EE", name: "Estonia", nameAr: "إستونيا", phoneCode: "+372" },
  { code: "SZ", name: "Eswatini", nameAr: "إسواتيني", phoneCode: "+268" },
  { code: "ET", name: "Ethiopia", nameAr: "إثيوبيا", phoneCode: "+251" },
  { code: "FJ", name: "Fiji", nameAr: "فيجي", phoneCode: "+679" },
  { code: "FI", name: "Finland", nameAr: "فنلندا", phoneCode: "+358" },
  { code: "FR", name: "France", nameAr: "فرنسا", phoneCode: "+33" },
  { code: "GA", name: "Gabon", nameAr: "الغابون", phoneCode: "+241" },
  { code: "GM", name: "Gambia", nameAr: "غامبيا", phoneCode: "+220" },
  { code: "GE", name: "Georgia", nameAr: "جورجيا", phoneCode: "+995" },
  { code: "DE", name: "Germany", nameAr: "ألمانيا", phoneCode: "+49" },
  { code: "GH", name: "Ghana", nameAr: "غانا", phoneCode: "+233" },
  { code: "GR", name: "Greece", nameAr: "اليونان", phoneCode: "+30" },
  { code: "GD", name: "Grenada", nameAr: "غرينادا", phoneCode: "+1473" },
  { code: "GT", name: "Guatemala", nameAr: "غواتيمالا", phoneCode: "+502" },
  { code: "GN", name: "Guinea", nameAr: "غينيا", phoneCode: "+224" },
  { code: "GW", name: "Guinea-Bissau", nameAr: "غينيا بيساو", phoneCode: "+245" },
  { code: "GY", name: "Guyana", nameAr: "غيانا", phoneCode: "+592" },
  { code: "HT", name: "Haiti", nameAr: "هايتي", phoneCode: "+509" },
  { code: "HN", name: "Honduras", nameAr: "هندوراس", phoneCode: "+504" },
  { code: "HK", name: "Hong Kong", nameAr: "هونغ كونغ", phoneCode: "+852" },
  { code: "HU", name: "Hungary", nameAr: "المجر", phoneCode: "+36" },
  { code: "IS", name: "Iceland", nameAr: "آيسلندا", phoneCode: "+354" },
  { code: "IN", name: "India", nameAr: "الهند", phoneCode: "+91" },
  { code: "ID", name: "Indonesia", nameAr: "إندونيسيا", phoneCode: "+62" },
  { code: "IR", name: "Iran", nameAr: "إيران", phoneCode: "+98" },
  { code: "IQ", name: "Iraq", nameAr: "العراق", phoneCode: "+964" },
  { code: "IE", name: "Ireland", nameAr: "أيرلندا", phoneCode: "+353" },
  { code: "IL", name: "Israel", nameAr: "إسرائيل", phoneCode: "+972" },
  { code: "IT", name: "Italy", nameAr: "إيطاليا", phoneCode: "+39" },
  { code: "JM", name: "Jamaica", nameAr: "جامايكا", phoneCode: "+1876" },
  { code: "JP", name: "Japan", nameAr: "اليابان", phoneCode: "+81" },
  { code: "JO", name: "Jordan", nameAr: "الأردن", phoneCode: "+962" },
  { code: "KZ", name: "Kazakhstan", nameAr: "كازاخستان", phoneCode: "+7" },
  { code: "KE", name: "Kenya", nameAr: "كينيا", phoneCode: "+254" },
  { code: "KI", name: "Kiribati", nameAr: "كيريباتي", phoneCode: "+686" },
  { code: "KP", name: "Korea (North)", nameAr: "كوريا الشمالية", phoneCode: "+850" },
  { code: "KR", name: "Korea (South)", nameAr: "كوريا الجنوبية", phoneCode: "+82" },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", phoneCode: "+965" },
  { code: "KG", name: "Kyrgyzstan", nameAr: "قيرغيزستان", phoneCode: "+996" },
  { code: "LA", name: "Laos", nameAr: "لاوس", phoneCode: "+856" },
  { code: "LV", name: "Latvia", nameAr: "لاتفيا", phoneCode: "+371" },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", phoneCode: "+961" },
  { code: "LS", name: "Lesotho", nameAr: "ليسوتو", phoneCode: "+266" },
  { code: "LR", name: "Liberia", nameAr: "ليبيريا", phoneCode: "+231" },
  { code: "LY", name: "Libya", nameAr: "ليبيا", phoneCode: "+218" },
  { code: "LI", name: "Liechtenstein", nameAr: "ليختنشتاين", phoneCode: "+423" },
  { code: "LT", name: "Lithuania", nameAr: "ليتوانيا", phoneCode: "+370" },
  { code: "LU", name: "Luxembourg", nameAr: "لوكسمبورغ", phoneCode: "+352" },
  { code: "MO", name: "Macau", nameAr: "ماكاو", phoneCode: "+853" },
  { code: "MG", name: "Madagascar", nameAr: "مدغشقر", phoneCode: "+261" },
  { code: "MW", name: "Malawi", nameAr: "مالاوي", phoneCode: "+265" },
  { code: "MY", name: "Malaysia", nameAr: "ماليزيا", phoneCode: "+60" },
  { code: "MV", name: "Maldives", nameAr: "المالديف", phoneCode: "+960" },
  { code: "ML", name: "Mali", nameAr: "مالي", phoneCode: "+223" },
  { code: "MT", name: "Malta", nameAr: "مالطا", phoneCode: "+356" },
  { code: "MH", name: "Marshall Islands", nameAr: "جزر مارشال", phoneCode: "+692" },
  { code: "MR", name: "Mauritania", nameAr: "موريتانيا", phoneCode: "+222" },
  { code: "MU", name: "Mauritius", nameAr: "موريشيوس", phoneCode: "+230" },
  { code: "MX", name: "Mexico", nameAr: "المكسيك", phoneCode: "+52" },
  { code: "FM", name: "Micronesia", nameAr: "ميكرونيزيا", phoneCode: "+691" },
  { code: "MD", name: "Moldova", nameAr: "مولدوفا", phoneCode: "+373" },
  { code: "MC", name: "Monaco", nameAr: "موناكو", phoneCode: "+377" },
  { code: "MN", name: "Mongolia", nameAr: "منغوليا", phoneCode: "+976" },
  { code: "ME", name: "Montenegro", nameAr: "الجبل الأسود", phoneCode: "+382" },
  { code: "MA", name: "Morocco", nameAr: "المغرب", phoneCode: "+212" },
  { code: "MZ", name: "Mozambique", nameAr: "موزمبيق", phoneCode: "+258" },
  { code: "MM", name: "Myanmar", nameAr: "ميانمار", phoneCode: "+95" },
  { code: "NA", name: "Namibia", nameAr: "ناميبيا", phoneCode: "+264" },
  { code: "NR", name: "Nauru", nameAr: "ناورو", phoneCode: "+674" },
  { code: "NP", name: "Nepal", nameAr: "نيبال", phoneCode: "+977" },
  { code: "NL", name: "Netherlands", nameAr: "هولندا", phoneCode: "+31" },
  { code: "NZ", name: "New Zealand", nameAr: "نيوزيلندا", phoneCode: "+64" },
  { code: "NI", name: "Nicaragua", nameAr: "نيكاراغوا", phoneCode: "+505" },
  { code: "NE", name: "Niger", nameAr: "النيجر", phoneCode: "+227" },
  { code: "NG", name: "Nigeria", nameAr: "نيجيريا", phoneCode: "+234" },
  { code: "MK", name: "North Macedonia", nameAr: "مقدونيا الشمالية", phoneCode: "+389" },
  { code: "NO", name: "Norway", nameAr: "النرويج", phoneCode: "+47" },
  { code: "OM", name: "Oman", nameAr: "عمان", phoneCode: "+968" },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", phoneCode: "+92" },
  { code: "PW", name: "Palau", nameAr: "بالاو", phoneCode: "+680" },
  { code: "PS", name: "Palestine", nameAr: "فلسطين", phoneCode: "+970" },
  { code: "PA", name: "Panama", nameAr: "بنما", phoneCode: "+507" },
  { code: "PG", name: "Papua New Guinea", nameAr: "بابوا غينيا الجديدة", phoneCode: "+675" },
  { code: "PY", name: "Paraguay", nameAr: "باراغواي", phoneCode: "+595" },
  { code: "PE", name: "Peru", nameAr: "بيرو", phoneCode: "+51" },
  { code: "PH", name: "Philippines", nameAr: "الفلبين", phoneCode: "+63" },
  { code: "PL", name: "Poland", nameAr: "بولندا", phoneCode: "+48" },
  { code: "PT", name: "Portugal", nameAr: "البرتغال", phoneCode: "+351" },
  { code: "QA", name: "Qatar", nameAr: "قطر", phoneCode: "+974" },
  { code: "RO", name: "Romania", nameAr: "رومانيا", phoneCode: "+40" },
  { code: "RU", name: "Russia", nameAr: "روسيا", phoneCode: "+7" },
  { code: "RW", name: "Rwanda", nameAr: "رواندا", phoneCode: "+250" },
  { code: "KN", name: "Saint Kitts and Nevis", nameAr: "سانت كيتس ونيفيس", phoneCode: "+1869" },
  { code: "LC", name: "Saint Lucia", nameAr: "سانت لوسيا", phoneCode: "+1758" },
  { code: "VC", name: "Saint Vincent and the Grenadines", nameAr: "سانت فنسنت والغرينادين", phoneCode: "+1784" },
  { code: "WS", name: "Samoa", nameAr: "ساموا", phoneCode: "+685" },
  { code: "SM", name: "San Marino", nameAr: "سان مارينو", phoneCode: "+378" },
  { code: "ST", name: "Sao Tome and Principe", nameAr: "ساو تومي وبرينسيب", phoneCode: "+239" },
  { code: "SA", name: "Saudi Arabia", nameAr: "السعودية", phoneCode: "+966" },
  { code: "SN", name: "Senegal", nameAr: "السنغال", phoneCode: "+221" },
  { code: "RS", name: "Serbia", nameAr: "صربيا", phoneCode: "+381" },
  { code: "SC", name: "Seychelles", nameAr: "سيشل", phoneCode: "+248" },
  { code: "SL", name: "Sierra Leone", nameAr: "سيراليون", phoneCode: "+232" },
  { code: "SG", name: "Singapore", nameAr: "سنغافورة", phoneCode: "+65" },
  { code: "SK", name: "Slovakia", nameAr: "سلوفاكيا", phoneCode: "+421" },
  { code: "SI", name: "Slovenia", nameAr: "سلوفينيا", phoneCode: "+386" },
  { code: "SB", name: "Solomon Islands", nameAr: "جزر سليمان", phoneCode: "+677" },
  { code: "SO", name: "Somalia", nameAr: "الصومال", phoneCode: "+252" },
  { code: "ZA", name: "South Africa", nameAr: "جنوب أفريقيا", phoneCode: "+27" },
  { code: "SS", name: "South Sudan", nameAr: "جنوب السودان", phoneCode: "+211" },
  { code: "ES", name: "Spain", nameAr: "إسبانيا", phoneCode: "+34" },
  { code: "LK", name: "Sri Lanka", nameAr: "سريلانكا", phoneCode: "+94" },
  { code: "SD", name: "Sudan", nameAr: "السودان", phoneCode: "+249" },
  { code: "SR", name: "Suriname", nameAr: "سورينام", phoneCode: "+597" },
  { code: "SE", name: "Sweden", nameAr: "السويد", phoneCode: "+46" },
  { code: "CH", name: "Switzerland", nameAr: "سويسرا", phoneCode: "+41" },
  { code: "SY", name: "Syria", nameAr: "سوريا", phoneCode: "+963" },
  { code: "TW", name: "Taiwan", nameAr: "تايوان", phoneCode: "+886" },
  { code: "TJ", name: "Tajikistan", nameAr: "طاجيكستان", phoneCode: "+992" },
  { code: "TZ", name: "Tanzania", nameAr: "تنزانيا", phoneCode: "+255" },
  { code: "TH", name: "Thailand", nameAr: "تايلاند", phoneCode: "+66" },
  { code: "TL", name: "Timor-Leste", nameAr: "تيمور الشرقية", phoneCode: "+670" },
  { code: "TG", name: "Togo", nameAr: "توغو", phoneCode: "+228" },
  { code: "TO", name: "Tonga", nameAr: "تونغا", phoneCode: "+676" },
  { code: "TT", name: "Trinidad and Tobago", nameAr: "ترينيداد وتوباغو", phoneCode: "+1868" },
  { code: "TN", name: "Tunisia", nameAr: "تونس", phoneCode: "+216" },
  { code: "TR", name: "Turkey", nameAr: "تركيا", phoneCode: "+90" },
  { code: "TM", name: "Turkmenistan", nameAr: "تركمانستان", phoneCode: "+993" },
  { code: "TV", name: "Tuvalu", nameAr: "توفالو", phoneCode: "+688" },
  { code: "UG", name: "Uganda", nameAr: "أوغندا", phoneCode: "+256" },
  { code: "UA", name: "Ukraine", nameAr: "أوكرانيا", phoneCode: "+380" },
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات", phoneCode: "+971" },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", phoneCode: "+44" },
  { code: "US", name: "United States", nameAr: "الولايات المتحدة", phoneCode: "+1" },
  { code: "UY", name: "Uruguay", nameAr: "أوروغواي", phoneCode: "+598" },
  { code: "UZ", name: "Uzbekistan", nameAr: "أوزبكستان", phoneCode: "+998" },
  { code: "VU", name: "Vanuatu", nameAr: "فانواتو", phoneCode: "+678" },
  { code: "VA", name: "Vatican City", nameAr: "الفاتيكان", phoneCode: "+379" },
  { code: "VE", name: "Venezuela", nameAr: "فنزويلا", phoneCode: "+58" },
  { code: "VN", name: "Vietnam", nameAr: "فيتنام", phoneCode: "+84" },
  { code: "YE", name: "Yemen", nameAr: "اليمن", phoneCode: "+967" },
  { code: "ZM", name: "Zambia", nameAr: "زامبيا", phoneCode: "+260" },
  { code: "ZW", name: "Zimbabwe", nameAr: "زيمبابوي", phoneCode: "+263" },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export function getCountryByPhoneCode(phoneCode: string): Country | undefined {
  return COUNTRIES.find((c) => c.phoneCode === phoneCode);
}

export function getCountryOptions(language: "en" | "ar" = "en") {
  return COUNTRIES.map((c) => ({
    value: c.code,
    label: language === "ar" ? c.nameAr : c.name,
  }));
}

export function getPhoneCodeOptions() {
  return COUNTRIES.map((c) => ({
    value: c.phoneCode,
    label: `${c.phoneCode} (${c.name})`,
    country: c.code,
  }));
}
