import type { PortalLang } from "@/lib/portal/i18n";

// ─── Bilingual UI strings (page-local). ───────────────────────────────
//
// Same pattern as the phase fill page's PAGE_STRINGS — kept inline rather
// than in a shared i18n module because the portal post-login flow has no
// translation infrastructure yet, the surface area is small, and a third
// language has never been on the table.
export const PORTAL_STRINGS = {
  en: {
    languageToggle: "العربية",
    attendeePortal: "Attendee Portal",
    loginDescEmail: "Sign in to view and manage your registration.",
    loginDescCode: "Check your inbox — we just emailed a 6-digit code.",
    emailAddress: "Email address",
    emailHelp:
      "Use the email you registered with. We'll send a code to sign you in.",
    sendMeCode: "Send me a code",
    sendingCode: "Sending code…",
    sixDigitCode: "6-digit code",
    sentTo: (email: string) => `Sent to ${email}.`,
    useDifferentEmail: "Use a different email",
    verifyAndSignIn: "Verify and sign in",
    verifying: "Verifying…",
    resendIn: (s: number) => `Resend code in ${s}s`,
    sending: "Sending…",
    didntGetItResend: "Didn't get it? Resend code",
    couldntSendCode: "Couldn't send a code. Please try again.",
    couldntReachServer: "Couldn't reach the server. Please try again.",
    validEmail: "Please enter a valid email address.",
    enter6Digit: "Please enter the 6-digit code from your email.",
    codeFailed: "That code didn't work. Try again.",
    signedInButCouldntLoad:
      "Signed in but couldn't load your registration. Please refresh.",
    logout: "Log Out",
    registrationStatus: "Registration Status",
    eventDate: "Event Date",
    venue: "Venue",
    confirmationCode: "Confirmation Code",
    downloadBadge: "Download Badge",
    confirmed: "Confirmed",
    pending: "Pending",
    waitlisted: "Waitlisted",
    cancelled: "Cancelled",
    yourDetails: "Your Details",
    edit: "Edit",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    noDetails: "No details to display.",
    failedToSave: "Failed to save changes",
    failedToConnect: "Failed to connect. Please try again.",
    additionalInfo: "Additional Information",
    additionalInfoDesc:
      "We need a few more details from you before the event. Each section opens on its own schedule.",
    open: "Open",
    notOpenYet: "Not open yet",
    closed: "Closed",
    locked: "Locked",
    completed: "Completed",
    required: "required",
    fillIn: "Fill in",
    view: "View",
    closes: (when: string) => `Closes ${when}`,
    opens: (when: string) => `Opens ${when}`,
    phaseClosedViewOnly: "This phase is closed — view-only.",
    notAvailable: "Not available for your registration.",
    cancelRegistration: "Cancel Registration",
    cancelRegistrationDesc:
      "If you can no longer attend, you can cancel your registration here.",
    cancelMyRegistration: "Cancel My Registration",
    cancelDialogQuestion: (eventName: string) =>
      `Are you sure you want to cancel your registration for ${eventName}? This action cannot be undone.`,
    keepRegistration: "Keep Registration",
    yesCancel: "Yes, Cancel",
    selectPlaceholder: "Select...",
    selectCountryPlaceholder: "Select country...",
    yes: "Yes",
    no: "No",
  },
  ar: {
    languageToggle: "English",
    attendeePortal: "بوابة الحضور",
    loginDescEmail: "سجّل الدخول لعرض تسجيلك وإدارته.",
    loginDescCode: "تحقق من بريدك — أرسلنا رمزًا من 6 أرقام للتو.",
    emailAddress: "البريد الإلكتروني",
    emailHelp:
      "استخدم البريد الذي سجّلت به. سنرسل رمزًا لتسجيل الدخول.",
    sendMeCode: "أرسل لي رمزًا",
    sendingCode: "جارٍ إرسال الرمز…",
    sixDigitCode: "الرمز المكوّن من 6 أرقام",
    sentTo: (email: string) => `أُرسل إلى ${email}.`,
    useDifferentEmail: "استخدام بريد آخر",
    verifyAndSignIn: "تحقق وسجّل الدخول",
    verifying: "جارٍ التحقق…",
    resendIn: (s: number) => `إعادة إرسال الرمز خلال ${s} ث`,
    sending: "جارٍ الإرسال…",
    didntGetItResend: "لم يصلك الرمز؟ إعادة إرسال",
    couldntSendCode: "تعذّر إرسال الرمز. يُرجى المحاولة مرة أخرى.",
    couldntReachServer: "تعذّر الوصول إلى الخادم. يُرجى المحاولة مرة أخرى.",
    validEmail: "يُرجى إدخال بريد إلكتروني صحيح.",
    enter6Digit: "يُرجى إدخال الرمز المكوّن من 6 أرقام من بريدك.",
    codeFailed: "لم يعمل الرمز. حاول مرة أخرى.",
    signedInButCouldntLoad:
      "تم تسجيل الدخول لكن تعذّر تحميل تسجيلك. يُرجى التحديث.",
    logout: "تسجيل الخروج",
    registrationStatus: "حالة التسجيل",
    eventDate: "تاريخ الفعالية",
    venue: "المكان",
    confirmationCode: "رمز التأكيد",
    downloadBadge: "تنزيل الشارة",
    confirmed: "مؤكد",
    pending: "قيد المراجعة",
    waitlisted: "في قائمة الانتظار",
    cancelled: "ملغى",
    yourDetails: "بياناتك",
    edit: "تعديل",
    saveChanges: "حفظ التعديلات",
    cancel: "إلغاء",
    noDetails: "لا توجد بيانات لعرضها.",
    failedToSave: "فشل حفظ التعديلات",
    failedToConnect: "فشل الاتصال. يُرجى المحاولة مرة أخرى.",
    additionalInfo: "معلومات إضافية",
    additionalInfoDesc:
      "نحتاج إلى بعض البيانات الإضافية قبل الفعالية. يفتح كل قسم وفق جدوله الخاص.",
    open: "مفتوح",
    notOpenYet: "لم يفتح بعد",
    closed: "مغلق",
    locked: "مقفل",
    completed: "مكتمل",
    required: "مطلوب",
    fillIn: "ابدأ",
    view: "عرض",
    closes: (when: string) => `يُغلق في ${when}`,
    opens: (when: string) => `يُفتح في ${when}`,
    phaseClosedViewOnly: "هذه المرحلة مغلقة — للعرض فقط.",
    notAvailable: "غير متاح لتسجيلك.",
    cancelRegistration: "إلغاء التسجيل",
    cancelRegistrationDesc:
      "إن لم تعد قادرًا على الحضور، يمكنك إلغاء تسجيلك من هنا.",
    cancelMyRegistration: "إلغاء تسجيلي",
    cancelDialogQuestion: (eventName: string) =>
      `هل أنت متأكد من إلغاء تسجيلك في "${eventName}"؟ لا يمكن التراجع عن هذا الإجراء.`,
    keepRegistration: "الإبقاء على التسجيل",
    yesCancel: "نعم، إلغاء",
    selectPlaceholder: "اختر...",
    selectCountryPlaceholder: "اختر الدولة...",
    yes: "نعم",
    no: "لا",
  },
} as const;

// The active-language string table (t) — what components receive as a prop.
export type PortalT = (typeof PORTAL_STRINGS)[PortalLang];
